### ISSUE TITLE
Docs show ReactSwitch as the component rather than Switch

### ISSUE THREAD

**Issue by kpaduch** [atomicpages/pretty-checkbox-react#1]
**Describe the bug**
In the docs, under the first Switch section, the `LiveEditor` for the `Switch` component shows the component as `ReactSwitch` rather than `Switch`.

**pretty checkbox react version**: 1.0.5

**To Reproduce**
1. Go to the docs page.
2. Go to the Switch example section.
3. Click on 'show code'
4. See `ReactSwitch`

**Expected behavior**
Example code should show `Switch` as the component.

**Comment by atomicpages** [comment]
Fixed in 80729d56ff626c025b425951d29343e0bf2be5fb. Thanks for making PCR better!
