### ISSUE TITLE
I followed the README but I don't have any frontend/styling rendered

### ISSUE THREAD

**Issue by antoine-nedelec** [atomicpages/pretty-checkbox-react#161]
npm version: 6.11.3
node version: 10.17.0

I installed as explained:
`npm install pretty-checkbox-react pretty-checkbox --save`

I then use my test route:
```
import React from 'react'
import { Checkbox } from 'pretty-checkbox-react';

class Test extends React.Component{
    render(){
        return(
            <section id="test">
                <Checkbox animation="smooth" shape="curve">Check me!</Checkbox>
            </section>
        )
    }
}

export default Test;
```

What did I miss ? It seems pretty straight forward in the `README`

**Comment by atomicpages** [comment]
You have to include `pretty-checkbox` either as an import or add it as a `link` tag in your index.html. The README is messed up right now -- sorry about that. I'll get this fixed.

**Comment by atomicpages** [comment]
Updated. Thanks!
