### ISSUE TITLE
Module not found: Can't resolve 'pretty-checkbox'

### ISSUE THREAD

**Issue by EgoistDeveloper** [atomicpages/pretty-checkbox-react#256]
**Describe the bug**
import 'pretty-checkbox'; giving this error

```
Module not found: Can't resolve 'pretty-checkbox' in 'C:\Users\e...
```

**pretty checkbox react version**: 2.0.0

**To Reproduce**
just add thist imports

import { Checkbox } from 'pretty-checkbox-react';
import 'pretty-checkbox';

**Desktop (please complete the following information):**

-   OS: Windows 10 Pro 64bit, 20H2, 19042.487
-   Browser: Opera
-   Version: 70.0.3728.154

**Comment by atomicpages** [comment]
👋 @EgoistDeveloper, did you install pretty-checkbox?

```sh
npm i pretty-checkbox --save # or
yarn add pretty-checkbox
```

If you're using webpack make sure you have [`css-loader`](https://webpack.js.org/loaders/css-loader/) installed, too.

**Comment by EgoistDeveloper** [comment]
@atomicpages, you are right that I missed. Actually I copied and pasted directly from npm's own page and at first I thought was an dependency. Problem solved.
