### ISSUE TITLE
Skip animation if checked by default

### ISSUE THREAD

**Issue by baba43** [atomicpages/pretty-checkbox-react#3]
First, thank you very much for this project. I love it so far! :-)

However, I found that whenever `checked` is set to true on initial load, the Checkbox is animating. Depending on the animation, that looks weird. If you have multiple checkboxes, it's like "Wtf is happening here" from the users perspective. 

I'm not sure if it's possible that easy, but I guess that the animation should be skipped when the Checkbox is checked on first load. 

What do you think?

**Comment by atomicpages** [comment]
Sounds reasonable to me, but in the [example on codesandbox](https://codesandbox.io/s/40v46649m0) I'm not seeing that 🤔

**Comment by baba43** [comment]
Your example doesn't animate at all? Because of the missing css?

**Comment by atomicpages** [comment]
The CSS is there. Can you help by proving a repro?

**Comment by atomicpages** [comment]
@baba43 closing this issue for now. LMK if you have an exact repro. Thanks for the contribution!
