### ISSUE TITLE
Can I customize the Colors somehow?

### ISSUE THREAD

**Issue by EfstathiadisD** [atomicpages/pretty-checkbox-react#329]
I implemented a small wrapper in our App, for the Radio. Everything works great. One point though. Can we customize the colors? They are a bit off. Thanks for your work.

**Comment by atomicpages** [comment]
@EfstathiadisD you sure can! Depending on what the desired result is you can:

1. Customize [scss variables](https://pretty-checkbox.netlify.app/docs/sass-customize) (see docs for more details)
2. Pass in a custom `color` prop value (using `// @ts-expect-error` to suppress any tsc errors) and writing CSS in your app to accommodate the custom color

  This might look something like: https://codepen.io/atomicpages/pen/ZEpvdLj?editors=0110

FWIW I'd go with the first option if you want to apply styles globally. LMK if something isn't clear/could be improved 👍

**Comment by EfstathiadisD** [comment]
Thank you so much. I missed that part. Will let you know how it goes, and will close the issue. Thanks!!
