### ISSUE TITLE
Checkbox grouping state with useCheckboxState

### ISSUE THREAD

**Issue by mystarrocks** [atomicpages/pretty-checkbox-react#419]
## 🐛 Bug Report

Attempting to use `useCheckboxState` to manage the state of related checkboxes causes it to work like a group of radio buttons, where only one of the options is checkable at a time, with attempts to enable other options having no effect. (It seems like the checked option is not uncheckable once checked as well.)

### Have you read the [Contributing Guidelines on issues](https://github.com/atomicpages/pretty-checkbox-react/blob/master/CONTRIBUTING.md)?

Yes.

## To Reproduce

1. Setup a group of checkboxes with values from an array
2. Use `useCheckboxState` to manage and print the checked option values
3. Once an option is checked, trying to check other options has no effect. Plus, the checked option is not uncheckable anymore

## Expected behavior

All the checkboxes are supposed to be checkable and uncheckable independently, with the state of each checkbox available via the `checkbox` state property.

## Actual Behavior

But only one of those checkboxes can be checked at a time; attempting to check other checkboxes or uncheck the checked option doesn't seem to have any effect, and somewhat works like radio buttons would.

## Your Environment

-   Chrome Version 91.0.4472.114 (Official Build) (64-bit)
-   Windows 10 desktop
- Dependencies:
```
"dependencies": {
    "@djthoms/pretty-checkbox": "3.1.0",
    "pretty-checkbox-react": "3.2.0",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-scripts": "4.0.3"
  }
```

## Reproducible Demo

https://codesandbox.io/s/crimson-shadow-3y8kb?file=/src/App.js

The code is essentially the same as the demo in the doc: https://pretty-checkbox-react.netlify.app/docs/main-concepts/controlled/#grouping-state. Interestingly, the code in the live editor there works the way it should.

**Comment by atomicpages** [comment]
Weird, `onChange` is running twice

**Comment by mystarrocks** [comment]
So checking an option causes it to be added to the state array (i.e push if it doesn't exist) the first time it's called, but subsequently be removed when it's called again (since it already exists, it's spliced)?

React's strict mode, coupled with running in development mode, could have something to do with it. I created my app using the `create-react-app`, and it came with the `React.StrictMode` in the `render`. Removing the strict mode ensures the `dispatch` is only run once, and everything works like it does in the doc live editor (perhaps strict mode is not enabled there). Actually, I might keep the strict mode and run in production mode to get around.

Apparently, it's the intended behavior according to the docs: https://reactjs.org/docs/strict-mode.html#detecting-unexpected-side-effects.

> Strict mode can’t automatically detect side effects for you, but it can help you spot them by making them a little more deterministic. This is done by intentionally double-invoking the following functions:
> 
> - Class component `constructor`, `render`, and `shouldComponentUpdate` methods
> - Class component static `getDerivedStateFromProps` method
> - Function component bodies
> - State updater functions (the first argument to `setState`)
> - Functions passed to `useState`, `useMemo`, or `useReducer`

> Note:
> 
> This only applies to development mode. _Lifecycles will not be double-invoked in production mode._

**Comment by atomicpages** [comment]
Hmmmm interesting, let me do some digging and follow up
