### ISSUE TITLE
How Do You Set an Initial "Checked" Value Using useRadioState()?

### ISSUE THREAD

**Issue by LukeVibes** [atomicpages/pretty-checkbox-react#472]
## 📚 Documentation

I cannot find anywhere in the documentation how to set an inital value / initial checked radio button when using the useRadioState(). Read through the documentation a couple times, could really use some help here figuring this out.

**Comment by atomicpages** [comment]
👋  thanks for the question! You can use pass `state` in the hook to set the initial state:

* [controlled usage](https://pretty-checkbox-react.netlify.app/docs/checkbox#boolean-checkboxes)
* [api docs](https://pretty-checkbox-react.netlify.app/docs/api/checkbox#usecheckboxstate-api)

I'll add an example the docs so this is more clear 😄 

```tsx
function App() {
  const checkbox = useCheckboxState({ state: true });

  return <Checkbox {...checkbox}>Checked: {checkbox.state + ''}</Checkbox>;
}
```
