### ISSUE TITLE
Help: How to limit the numbers of checkboxes that are checked?

### ISSUE THREAD

**Issue by wklenk** [atomicpages/pretty-checkbox-react#575]
Hello,
given I have a page with 10 checkboxes, but the user is only allowed to check 3 of them.
Is there an elegant way to avoid that a forth checkbox can be checked? Maybe just be intercepting the change event and not allowing it to mark the checkbox as checked? Using locked/disabled state is not an option, as the user still needs to be able to uncheck other checkboxes. I tried out several approaches, I can count the number of checked checkboxes, but I don't find a way how to avoid that the checkbox is checked when the user clicks on it.

**Comment by atomicpages** [comment]
Hey there, can you clarify the use case? There are a11y reasons why we'd want to use `disabled` or `locked` versus trapping the `onChange` event. Happy to help if you can expand a bit more 😄

**Comment by wklenk** [comment]
If the user is allowed to check at most 3 of 10 checkboxes, and I "lock" the checkboxes after the third checkbox, the user is stuck, because - as the checkboxes are locked - he cannot uncheck one to change his choice. That's the reason why I think "lock" or "disable" is not appropriate.

**Comment by atomicpages** [comment]
Ah, I see; a pragmatic example is pizza toppings: you can only pick. In that case `lock` or `disabled` is appropriate for accessibility reasons. You can, however, trap the `onChange` event and block it but be sure to add `aria-disabled` for screen readers. See [managing state without hooks](https://pretty-checkbox-react.netlify.app/docs/main-concepts/controlled/#managing-state-without-hooks) for more details.

At a high level:

- provide an array an objects with a `disabled` field
- track state via `useState` or your preferred state management solution
- intercept the `onChange` and prevent default after three selections
  - update subsequent checkboxes with `aria-disabled`

```tsx
const [checked, setChecked] = useState<string[]>([]);

const onChange = (e) => {
  if (checked.length === 3) {
    e.preventDefault();
  }
}

// ...
items.map(item => {
  return (
    <Checkbox label={item.label} aria-disabled={item.disabled} checked={checked.includes(item.value)}>
      {item.value}
    </Checkbox>
  );
});
```
