### ISSUE TITLE
Doesn't work in next.js typescript

### ISSUE THREAD

**Issue by chopinballadeno4** [atomicpages/pretty-checkbox-react#725]
## 🐛 Bug Report

Radio isn't working in next.js using typescript

### Have you read the [Contributing Guidelines on issues](https://github.com/atomicpages/pretty-checkbox-react/blob/master/CONTRIBUTING.md)?

yes !

## To Reproduce

1. Create new react/next.js app with npx create-react-app <name> or npx create-next-app --use-npm (Typescript)
2. Install PCR with npm i pretty-checkbox pretty-checkbox-react
3. Create new component with <Radio>Foo</Radio>

## Expected behavior

should display Radio with style

## Actual Behavior

![image](https://user-images.githubusercontent.com/70872563/185291756-874dd52c-4618-42d0-b7b9-c5c2d8804a14.png)
![image](https://user-images.githubusercontent.com/70872563/185291801-7eb7d415-8c84-4719-b4fb-d211b58b8116.png)
![image](https://user-images.githubusercontent.com/70872563/185291841-cd170ab4-a3a0-4f96-beec-be58852aa383.png)

## Your Environment

node -v 16.15.0
"react": "18.2.0",
"react-dom": "18.2.0"

**Comment by lhmson** [comment]
I can think of 2 ways to bypass this
1. Change the props type of `PaymentMethodRadio` to `any` 
2. Refer to `node_modules\pretty-checkbox-react\dist-types\components\radio\useRadioState.d.ts` then change **setState** definition to `setState: React.Dispatch<React.SetStateAction<string | boolean | undefined>>`

I'm not sure if this affects any other function but in case it does not, just wait for a PR to fix it :)

**Comment by atomicpages** [comment]
👋 , do you mind providing a tiny example showing the issue? https://stackblitz.com/ or  https://codesandbox.io/ would work great so I can better help out 🙏

**Comment by atomicpages** [comment]
Confirmed it works with next.js + typescript. See example here: https://nextjs-s41ygn--3000.local-credentialless.webcontainer.io/ if you have a specific use case please post here 🙏
